#!/bin/bash

#uncomment for debugging
#set -x -v
PARMS=( $@ )
DISTDIR=${PARMS[0]}
FILE=${PARMS[1]}
URI=${PARMS[2]}

shift 3
echo $@
GENTOO_MIRRORS=$@
m=( $(echo ${GENTOO_MIRRORS//\//_slash_}) )
URI1=${URI//\//_slash_}
pushd $DISTDIR
CMMMD="aria2c -c -j 15 -s 15 -x 15   --remote-time   --http-accept-gzip -d $DISTDIR  -o $FILE ${URI} ${URI1/${m[0]}/${m[1]}} ${URI1/${m[0]}/${m[2]}} ${URI1/${m[0]}/${m[3]}} ${URI1/${m[0]}/${m[4]}}"
eval ${CMMMD//_slash_/\/}
